### ISSUE TITLE
请问程序是完整的吗，readme中提供的清华大学云盘链接无法打开，运行程序得到如下报错

### ISSUE THREAD

**Issue by uncle-tou** [zhanghx0905/capstone#5]
Traceback (most recent call last):
  File "train.py", line 38, in <module>
    adj, features, y_train, y_val, y_test, train_mask, val_mask, test_mask, train_size, test_size = load_corpus(cfg.dataset)
  File ".\capstone-master\text_gcn\utils.py", line 135, in load_corpus
    with open("./data/ind.{}.{}".format(dataset_str, names[i]), 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: './data/ind.r8.x'

**Comment by zhanghx0905** [comment]
过去了好几年，已经忘记了，云盘保存的checkpoint也丢失了。只能您自己读代码研究一下了
